test/hooks/common.js

Express tests have been flaky because spans are sometimes a few MS shorter than expected duration.

Add forgiveness on both sides of expected span durations on tests

---

bin/run-test.sh
test/standalone/test-trace-cluster.js
test/test-utils.js

Also moved cluster test to standalone so hooks can be run in the same mocha invocation as unit tests.

Run standalone tests on travis

---

lib/trace-writer.js
test/hooks/common.js
test/test-span-data.js

This will avoid a huge stringify call holding down the cpu on publish.

stringify spans when they're queued

---

lib/hooks/core/hook-http.js
test/hooks/test-trace-http.js
test/test-trace-agent.js

We already have other tests guaranteeing the formatting of the headers. This just ensures that code path is exercised and the api is called correctly.

Test coverage for adding context to headers

---

lib/hooks/userspace/hook-express.js
package.json
test/standalone/test-index.js

Unit and non-interference tests pass with these changes. I don't believe it is necessary to update unit tests with full coverage of the method interface as the code paths are fully shared. @ofrobots PTAL.

Patched express on public interface

---

.travis.yml

We have moved over to version 2 as it is referred to after
the iojs/node merge.
Fixes #67

Removed iojs from travis test targets

---

lib/hooks/core/hook-http.js
lib/hooks/userspace/hook-mongodb-core.js
lib/trace-agent.js
test/standalone/test-index.js

Previously, labels were passed to start and end span calls
with the structure [{ key: 'key', value: 'val' }]. This has been
replaced with the more concise { key: 'val' } structure.
@ofrobots PTAL.

Accept labels as objects on start and end span

---

lib/hooks/userspace/hook-express.js
lib/hooks/userspace/hook-hapi.js
lib/hooks/userspace/hook-restify.js
test/standalone/test-agent-stopped.js

A null reference was occuring when the agent disabled after
attaching express middleware. Middleware now verifies that
the agent is enabled before starting the trace.
Fixes #70 
@ofrobots PTAL

Fixes null reference in express

---

config.js

Added two new flags:
GCLOUD_TRACE_DISABLE: boolean, if set the agent will not enable
GCLOUD_TRACE_LOGGING: numeric, sets the trace log level
Fixes #72

Check env vars for enabling and log levels

---

package.json

It is required for the express hook. This wasn't caught by CI since all dev dependencies are installed there.
@ofrobots PTAL

Moved methods dep from dev to normal dependency

---

config.js
index.js
test/standalone/test-env-disable.js
test/standalone/test-env-log-level.js
test/standalone/test-env-project-id.js
test/standalone/test-index.js
test/standalone/test-invalid-project-id.js

There was another problem with the enabled config option
being completely ignored this time. This patch fixes the bug and
introduces stand alone tests for each of our current environment
variable flags.
@ofrobots PTAL.

Added tests for enviroment variables

---

lib/hooks/index.js
lib/hooks/userspace/hook-express.js
lib/hooks/userspace/hook-hapi.js
lib/hooks/userspace/hook-mongodb-core.js
lib/hooks/userspace/hook-redis.js
lib/hooks/userspace/hook-restify.js
test/hooks/test-hooks-index.js

This patch uses module internals to load the package.json file
associated with required modules and uses them to determine module
versions instead of checking for the presence of non-public facing
api functions.
Fixes #24.

Check framework versions using package.json

---

lib/hooks/index.js

The module file finder is able to search with respect to a
provided parent module allowing us to find modules that are
not in the load path of the primary application module.
Fixes #82

Resolve all module scripts correctly

---

lib/hooks/userspace/hook-express.js
lib/hooks/userspace/hook-hapi.js
lib/hooks/userspace/hook-mongodb-core.js
lib/hooks/userspace/hook-restify.js

Since Redis is still in 0.x, I'm leaving minor version requirement there as there could be breaking changes on minor differences.

Relaxed required version checks to major version only

---

config.js
lib/trace-writer.js
test/standalone/test-trace-writer.js

This also fixes a bug where we were ignoring `bufferSize` in config due to a typo. Arrggg.

Enable trace throttling

---

lib/hooks/core/hook-http.js
lib/hooks/index.js
lib/hooks/userspace/hook-express.js
lib/hooks/userspace/hook-hapi.js
lib/hooks/userspace/hook-mongodb-core.js
lib/hooks/userspace/hook-redis.js
lib/hooks/userspace/hook-restify.js
test/hooks/test-hooks-index.js
test/hooks/test-hooks-interop-mongo-express.js

ismaster checks occuring on behalf of incoming requests were escaping. By binding listeners on the connection pool event emitter to the current cls context, we can correctly attribute the work that they do.
Fixes #96

Patch the mongo connection pool

---

config.js
lib/trace-agent.js
lib/tracing-policy.js
test/test-trace-policy.js

Introduced a new tracing policy that ignores all traces occuring at
designated paths before sampling occurs to prevent ignored urls from
being sampled.
Fixes #103.

Possible to omit all traces at specified urls

---

lib/hooks/userspace/hook-redis.js
test/hooks/fixtures/redis2/index.js
test/hooks/fixtures/redis2/package.json
test/hooks/test-hooks-index.js
test/hooks/test-trace-redis.js

This also tests the patching of multiple versions of a module
simultaneously. Also, removed a test that was not testing
agent functionality (just a property of redis).
Fixes #92.

Run redis v2 against unit tests

---

lib/hooks/index.js
lib/hooks/userspace/hook-redis.js
test/hooks/fixtures/redis2/package.json

This fix should allow us to pick up future versions of redis on the 2.x
line.
Fixes #123

Support for Redis 2.3

---

lib/cls.js
lib/hooks/core/hook-http.js
lib/hooks/userspace/hook-mongodb-core.js
lib/hooks/userspace/hook-redis.js
lib/trace-agent.js
test/standalone/test-hooks-sample-warning.js

Mongo and redis no longer warn that tracing happened outside of a
supported framework when root spans are sampled.
Fixes #137.

No more warnings when root spans are sampled

---

.jshintignore
config.js
test/standalone/test-default-ignore-ah-health.js

A few other minor issues also fixed at the same time
* BSD `sed` on a mac requires an argument for `-i`.
* Don't run jshint on test/hooks/fixtures

ignore /_ah/health by default

---

lib/hooks/core/hook-http.js
lib/span-data.js
lib/trace-agent.js
test/standalone/test-trace-header-context.js

Root spans that inherit their trace context from incoming headers are
now properly identified as root spans and logged. Independently this
fixes and tests a bug where outgoing contexts were not attached to all
requests.
Fixes #152.

Identify root spans with inherited context

---

lib/hooks/core/hook-http.js
lib/hooks/userspace/hook-express.js
lib/hooks/userspace/hook-hapi.js
lib/hooks/userspace/hook-mongodb-core.js
lib/hooks/userspace/hook-mysql.js
lib/hooks/userspace/hook-redis.js
lib/hooks/userspace/hook-restify.js
test/standalone/test-hooks-no-project-num.js

The crash is not reproducible for the other frameworks as those patches
do not persist on long lived objects and thus execute after hooks have
been disabled. This PR also fixes a race condition crash that could
occur if hooks were disabled between the start and end of a single span
(resulting in a null dereference of the agent).
Fixes #149

Fix mongodb crash if project num isn't found

---

index.js
lib/trace-labels.js
lib/trace-writer.js
test/standalone/test-agent-metadata.js

Module and version drop down boxes in the Trace UI use these labels to allow
filtering by module and version. For GCE, GKE we use the hostname as the module
to allow the same functionality in the UI.
Fixes: #169

attach GAE labels when available

---

lib/hooks/userspace/hook-redis.js
test/hooks/fixtures/redis2-hiredis0.4/package.json
test/hooks/fixtures/redis2/package.json

This is a work-arounds a change is redis 2.4 that breaks our tracing.

restrict redis support to <= 2.3.x

---

lib/trace-writer.js
test/standalone/test-agent-metadata.js

We were sending undefined as the GAE_MODULE label.
@matthewloring ptal.

fix GAE_MODULE fall-back to local hostname

---

index.js

This ensures that the code async APIs get patched befored anything in
user-space can get loaded and interfere with tracing. This is a
problem with request in particular as it caches setImmediate.
Fixes: #182
Lands: #187

load cls before all else

---

bin/run-test.sh
lib/hooks/index.js
lib/hooks/userspace/hook-koa.js
test/hooks/fixtures/koa1/index.js
test/hooks/fixtures/koa1/package.json
test/standalone/test-trace-koa.js

Experimental tracing hooks for koa

---

lib/hooks/index.js
lib/trace-writer.js

Detecting modules loaded before the trace agent now causes an error to
be logged (up from warning). Message logged for full trace buffer now
states this as the cause.
Fixes #194

Updated logging in a few places

---

index.js
test/fixtures/test-config.js
test/fixtures/test-config.json
test/standalone/test-config-json.js
test/standalone/test-config-priority.js
test/standalone/test-config-relative-path.js

The environment variable name for the config file has been updated to
the more general GCLOUD_CONFIG. The config file is also now structured
to support separate configs for each of the profile, debug, and trace
agents.

Change config format to support multiple agents

---

index.js
test/fixtures/start-agent.js
test/standalone/test-modules-loaded-before-agent.js

Add additional logging to report any modules loaded before the trace
agent even if they are not modules that we patch directly.
Fixes #187.

Warn about modules loaded before trace agent

---

.jshintrc
lib/constants.js
lib/hooks/userspace/hook-express.js
lib/hooks/userspace/hook-hapi.js
lib/hooks/userspace/hook-koa.js
lib/hooks/userspace/hook-restify.js
lib/trace-agent.js
test/standalone/test-trace-options.js

Previously, if the app server decided to ignore a request that our sampling process decided to trace, the span would not be rendered in the UI because the parent span to the root reported by the trace agent was not present. Inversely, if the app server decided to trace a request that our sampling process decided to ignore, an empty root span would show up in the UI without any additional Node.js information.
To remedy these issues, we have adopted the following semantics:
If there is no trace context header; we use our sampling
If there is a trace context header, but no options or non-numeric options; we use our sampling
If there is a trace context header with options, and options is a number; we use that to decide.

Respect incoming trace enabled options

---

lib/hooks/userspace/hook-mysql.js
package.json
test/standalone/test-mysql-pool.js

If the mysql connection pool is accessed during a request we drop
context. By patching getConnection we can avoid this.
Fixes the mysql component of #221

Patch mysql connection pool

---

config.js
lib/trace-agent.js
test/standalone/test-trace-options-sampling.js

This will lead to some empty root spans appearing in the UI if the app
server decides to trace an incoming request but the agent decides not to
sample it. This is deemed preferable to always accepting incoming trace
headers as we cannot always trust their origin.
Fixes #234

Enforce sampling policy regardless of headers

---

.travis.yml
README.md
index.js
test/hooks/common.js
test/non-interference/express-e2e.js
test/non-interference/http-e2e.js
test/non-interference/mongo-e2e.js
test/non-interference/restify-e2e.js
test/standalone/test-agent-metadata.js
test/standalone/test-agent-stopped.js
test/standalone/test-env-project-id.js
test/standalone/test-hooks-no-project-num.js
test/standalone/test-index.js
test/standalone/test-invalid-project-id.js
test/standalone/test-no-self-tracing.js
test/standalone/test-trace-writer.js
test/test-span-data.js
test/test-trace-agent.js

Use GCLOUD_PROJECT instead of GCLOUD_PROJECT_NUM

---

README.md

Add documentation to the README for the use of service account keys for
authorization as an alternative to logging in with the gcloud cli.
Fixes #248

Document service account keys

---

lib/hooks/userspace/hook-grpc.js

This was tested by:
1. Installing a new grpc fixture from grpc@master.
2. Updating `hook-grpc.js` to accept the version range `0.13 - 0.14 || 0.15.0-dev`.
3. Running `test/standalone/test-grpc-context.js` including this new fixture.
4. After passing tests, updating the accepted version range to `0.13 - 0.15`.

Add support for pre-release grpc v0.15

---

lib/hooks/core/hook-http.js
lib/trace-agent.js
test/standalone/test-trace-header-context.js
test/test-trace-agent.js

We currently only emit a trace header on the requests that we sample. This change causes all such outgoing traced requests to set the trace enabled bit.

Set outgoing trace enabled header always

---

config.js

Provide more details on what each of the options for config.trace.onUncaughtException mean for the user's application.
R=@matthewloring, @cristiancavalli.

update the description for onUncaughtException

---

lib/hooks/userspace/hook-grpc.js

This was tested by:
1. Installing a new grpc fixture from grpc@master.
2. Updating `hook-grpc.js` to accept the version range `0.13 - 0.15 || 1.1.0-dev`.
3. Running `test/standalone/test-grpc-context.js` including this new fixture.
4. Running `test/hooks/test-trace-grpc.js` including this new fixture.
5. After passing tests, updating the accepted version range to `0.13 - 1`.

Add support for pre-release grpc v1.1.0

---

test/hooks/test-trace-mongoose.js

Mongoose updated and dropped support for its own promise library
mpromise. The test will now rely on builtin promises.

Fix mongoose promise deprecation

---

config.js
lib/trace-agent.js
test/test-trace-agent.js

Hi,
Short background: I've been debugging for a week an issue that started occurring last week in our GCP projects after the Google Load Balancers got an update.
The LB doesn't respect my already set "x-cloud-trace-context" -header and overwrites it.
This makes our Traces to disappear because of our complex infrastructural setup.
This simple patch allows us to continue the usage of this module without any problems.
This will help others also who have similar infrastructural setup (I can write a description of it, if necessary).
Hopefully this could be included in the main package, so I do not need to keep installing this with npm from my github.

Allow ignoring the requests Context header

---

README.md

Specify that application default credentials is only recommended for
development/testing environments.
Fixes #283

Clarify use of application-default credentials

---

lib/hooks/userspace/hook-grpc.js
lib/trace-agent.js
test/hooks/common.js
test/hooks/test-trace-grpc.js
test/standalone/test-grpc-context.js

This change introduces gRPC server function tracing. In addition to the timespan itself, the arguments, return results, and any metadata or errors are written in trace spans as well.

Implement gRPC Server Tracing

---

README.md
index.js
lib/trace-agent.js
test/standalone/test-index.js

The trace agent now exposes a new method `runInRootSpan` with a similar signature to `runInSpan`. It is intended for users to create custom top-level spans.

Added Custom Root Spans

---

lib/hooks/index.js
lib/hooks/userspace/hook-connect.js

This adds support for `connect`, which is used by `swagger-tools` (#304).
I had to add an interception concept here, because `connect` returns a function as it's `module.exports`, which means the traditional `patch`/`unpatch` does not work (as far as I could tell).

Intercept connect module

---

lib/hooks/userspace/hook-connect.js
test/hooks/fixtures/connect3/index.js
test/hooks/fixtures/connect3/package.json
test/hooks/test-trace-connect.js

Connect spans now record the protocol and hostname as a prefix to the original URL.
Also, I've added some tests that are pretty similar to the Express ones.

Change connect trace URL prefix and add tests for connect hook

---

README.md

This fixes a small typo where present tense is used instead of past tense.

Fix a grammar typo

---

config.js
index.js
package.json
src/trace-writer.js
test/hooks/test-hooks-index.js
test/standalone/test-agent-metadata.js
test/standalone/test-config-credentials.js
test/standalone/test-invalid-project-id.js
test/standalone/test-no-self-tracing.js

Removed all dependencies on cloud-diagnostics-common, replacing with equivalent functionality in cloud-common.

Removed dependency on cloud-diagnostics-common

---

src/hooks/userspace/hook-grpc.js
src/hooks/userspace/hook-mysql.js

If either of these modules switch to lazily importing any of our patched
files, we would fail to set the agent in some cases.

Ensure agent is always set for mysql/grpc

---

src/hooks/userspace/hook-grpc.js
test/hooks/common.js
test/hooks/test-trace-grpc.js

Calling gRPC server functions would clobber references to root span objects (causing them to either never end, or end at the wrong time) because they are stored in the scope of the patching function (`wrapUnary`, `wrapClientStream`, etc.).
This change fixes that by putting a reference to the root span in the scope of the `func` handler, so a root span can exist per gRPC call.
In addition, unit tests were added/modified:
- to ensure that interleaved gRPC call traces don't interfere with one another.
- to ensure that context is being propagated correctly to call handlers, by creating child spans in these handlers.
- to ensure that gRPC server call traces include the correct subset of stack frames.

Fix gRPC Server root span reference issue

---

src/hooks/userspace/hook-grpc.js
test/hooks/common.js
test/hooks/test-trace-grpc.js

* Slight `wrap`-function doc change to reflect previous changes
* Comments summarizing start and end span points
* Check `agent.shouldTrace` to determine whether span should actually be started
* Renamed `func` object to `serverMethod` internally (less confusion)
* No longer dealing with `arguments` - `apply` calls changed to `call` with actual arguments
* Collapse consecutive `if` statements with identical conditions
* `switch` instead of `if...else if` statement for picking `wrap` function

Follow-Up Fixes for gRPC

---

src/trace-plugin-interface.js
src/trace-plugin-loader.js

I believe this is needed for some tests to pass since the agent might be started with no namespace. Also, added closed flag to be able to log errors if spans are ended multiple times.

Plugin API: Additional comments, logging, handling no namespace

---

src/trace-plugin-interface.js

Introduces `Transaction.prototype.createChildSpan` (and `api.prototype.createChildSpan`). Would like to rip out `runInChildSpan` if possible, it no longer has a reason to be used.

Plugin API: Add createChildSpan

---

src/trace-plugin-loader.js
src/util.js
test/test-plugin-loader.js

- Warn if module version is unsatisfied by plugin
- Fix possible bad behavior if `patch.versions` doesn't exist
- Fix programming error related to patch sets
- Store multiple module versions
- Add plugin loader tests

Plugin API: Loading Improvements

---

src/trace-plugin-interface.js

Updated API to refer to root spans everywhere.
As an additional note - the interface and implementation of `ChildSpan` and `RootSpan` are identical, however they may diverge if the implementation details of each change locations in the future. I wouldn't be against merging them, if anyone feels strongly about doing so then please let me know.

Plugin API: Rename Transaction -> Root Span

---

src/trace-plugin-interface.js

`shouldTrace` isn't being called unless `options.url` is defined. This fixes that, so that `shouldTrace` is always being called.
In addition, `options.url` is used in place of `options.name` if it's not defined. This makes it so that if a trace's name is its URL, both fields don't have to be supplied.

Bugfix for creating root spans through plugin API

---

index.js
src/trace-agent.js
src/trace-plugin-loader.js
test/non-interference/express-e2e.js
test/non-interference/start-agent.js
test/test-unpatch.js

The combination of having a plugin for a certain module (for express, restify, presumably others) and changes in how the agent is started and stopped seem to produce failures in the unit tests for that module. This was observed specifically in express and restify (in the latter, the error code was not reported correctly). Note that these tests are only run on CI in Node v0.12, but the same issues arise in other Node versions.
This fix should resolve that, but in the meantime, I'm looking into why this is the case.

Fix for external unit test failures

---

src/trace-writer.js

Add stack trace to service network errors

---

bin/docker-trace.sh

This change adds a script to run docker containers to support local unit testing. It's not needed on any CI.
`./bin/docker-trace.sh start` starts docker containers listening locally for mongoDB, redis, and MySQL connections.
`./bin/docker-trace.sh stop` stops them (though, in a somewhat unsafe way).

Add docker start/stop script for DB unit tests

---

config.js
src/trace-plugin-loader.js
test/test-plugin-loader.js

This change seeks to introduce not loading a plugin if its path is falsey.
This would make it possible to stop built-in plugins from loading. While we have previously discussed that we don't necessarily know what use cases we are supporting with this, I can name one now: I want to be able to run per-plugin benchmarks, and it would be really neat to isolate a single plugin at a time.
I think falsey is the best approach here because we know for sure that it's not a valid path.
@GoogleCloudPlatform/node-team PTAL.

Plugins with falsey paths don't get loaded

---

src/trace-plugin-loader.js
test/test-plugin-loader.js

Throw for plugin patches
- with both `patch` and `intercept`
- with neither
Warn for plugin patches
- with `unpatch` and `intercept` (should this throw as well?)
Open to any thoughts regarding severity level.

Plugin loader throws for plugins with glaring issues

---

CHANGELOG.md

This version does not include any changes since 1.0.0-rc1. It is the first publish to the new module name: @google-cloud/trace-agent.

1.0.0 Release Proposal

---

config.js
src/plugins/plugin-google-gax.js
test/plugins/fixtures/google-cloud-speech0.6/index.js
test/plugins/fixtures/google-cloud-speech0.6/package.json
test/plugins/test-trace-google-gax.js
test/test-config-plugins.js

This should allow tracing of pubsub, vision, monitoring, spanner,
speech, and nlp.

Context propagation for google-gax

---

src/plugins/plugin-grpc.js
src/trace-agent.js
src/util.js
test/plugins/test-trace-grpc.js

Fix for #434. This changes the gRPC plugin to add the `'x-cloud-trace-context'` metadata field to outgoing gRPC requests, and read it from incoming gRPC requests.

Distributed tracing support in gRPC

---

src/plugins/plugin-redis.js
test/plugins/fixtures/redis2.x/package.json
test/plugins/test-trace-redis.js

The only change needed for this is expanding the semver condition range for the 2.6 patch to include 2.7 as well.

Add Support for redis 2.7

---

src/plugins/plugin-hapi.js

Currently, the config ignoreUrls won't work when working with a Hapi server, since the url field does not exist when `runInRootSpan` is called.
See #446

Add url field to hapi middleware options

---

README.md
bin/run-test.sh
test/test-agent-metadata.js

The `google-gax` plugin unit test doesn't work on Node v0.12 + gRPC v1.2, so this change stops it from running. I've also added a disclaimer in the README stating that in general, we won't officially provide support for modules that depend on gRPC (or gRPC itself) if the application is running on a version of Node that that version of gRPC does not support.

Stop running google-gax unit test on v0.12

---

bin/clean-test-fixtures.sh
bin/install-test-fixtures.sh
bin/run-test.sh

This change adds the `bin/install-test-fixtures.sh` and `clean-test-fixtures.sh` files.
In particular, `bin/run-test.sh` calls `bin/install-test-fixtures.sh` which only does an `npm install` on fixture directories that do not have a `node_modules` directory.
This should not alter how tests are run in the CI, but should make local testing faster.

Allow Manual Test Fixture Management

---

src/trace-labels.js

The trace service recently changed the names of common labels to reduce
label key size. Updating these to use the new expected names.

Update trace label names

---

package.json

Now that npm has download stats for scoped modules, we no longer need this.

drop dependency on dummy counter module

---

test/test-grpc-context.js

gRPC 1.3 now throws on undefined.
Fixes: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/473

pass valid TestRequest message in grpc test

---

src/trace-plugin-loader.js
test/test-plugin-loader.js

Intercepts are only being done for top-level modules -- in other words, files being required internally within modules won't be intercepted.
In this fix, we cache modules that were intercepted in a separate object so that when loaded, we'll return the replaced value instead.

patching: fix module-internal requires not being intercepted

---

src/plugins/plugin-http.js

Fix for https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/481

http: return response object for chaining #481

---

src/plugins/plugin-hapi.js
src/plugins/plugin-koa.js
test/plugins/test-trace-connect.js
test/plugins/test-trace-express.js
test/plugins/test-trace-hapi.js
test/plugins/test-trace-koa.js
test/plugins/test-trace-restify.js

This is an attempt to address #477.
Currently checking if the same problem is present in other web frameworks (it's not in express as far as I can tell).

hapi/koa: End span when request is aborted

---

system-test/trace-express.js

We no longer have GOOGLE_APPLICATION_CREDENTIALS defined on travis and this test was sensitive to picking up the credentials from there.

fix credentials on system-test

---

.gitignore
.travis.yml
appveyor.yml
src/plugins/plugin-http.js
test/non-interference/http-e2e.js
test/plugins/test-trace-http.js

Node 8 is being tested now. Because of changes in Node core, we were no longer able to trace http.get calls. This PR includes a fix for that too.

start testing against Node 8

---

.gitignore
package-lock.json
package.json
yarn.lock

New versions of got do not play well with async listener. The bug
tracking this issue is here:
https://github.com/othiym23/async-listener/issues/112.
Got is only a dev dependency used by the system tests so relying on an
older version should be fine.

Roll back to old version of got

---

doc/trace-api.md
src/trace-api.js

- Fix various comment typos such as
successfully and falsy to stay consistent
throughout the codebase.

Typo fixes throughout a few comments

---

doc/trace-api.md

- The link in the TraceApi documentation was referencing
a local directory path but instead needed to be out
one directory.
- The line number referencing runInRootSpan is now on L42
ipo L35.  That said, in the future it may make sense to
remove the line number because keeping all of this in sync
is borderline maintenance pain.

Fix document source link

---

src/span-data.js

In cases where context is misattributed, bugs manifest with spans being attributed to an already closed span. It would be good to have a warning for these as a mechanism to debug.

warn when creating a child of a closed span

---

test/non-interference/http-e2e.js

Check for, and use the requested flags in the test files.
A few tests on Node master now require `--expose-internals`.

test: fix http interference tests

---

src/trace-api.js
test/test-index.js

Using the custom span API while the Trace Agent is disabled causes an error, since the agent is in an inconsistent state where it uses its enabled implementation without being explicitly enabled. (Note that this doesn't affect plugin usage because plugins are not loaded if the trace agent is disabled).
This change adds an `active_` field in TraceAgent instead of relying on whether the namespace exists. This ensures that the agent is actually disabled completely.

fix: add explicit active flag in trace agent

---

index.js

On Windows, the Trace Agent emits a warning saying that it was loaded before itself, due to module names using system-dependent org/module separators.

fix: don't warn about trace loading before itself on windows

---

src/trace-api.js
test/non-interference/http-e2e.js

`this.active_` guards are unnecessary in `TraceApi`. This change removes them.

refactor: remove active_ flag

---

README.md
index.js
test/fixtures/test-config.js
test/test-config-priority.js

- This implementation provides a means of setting
the configuration file from the environment variable,
GCLOUD_TRACE_CONFIG.
Addresses: #525 
If the decision is to change the order, I can do that as well and update the tests accordingly.

feat: Add GCLOUD_TRACE_CONFIG env config

---

test/non-interference/http-e2e.js

This change removes failing http2 tests introduced in node v8.4.0 from our CI. There is no need to run https/http2 tests on every PR.

Fix http-e2e for node 8.4.0

---

.travis.yml
appveyor.yml
circle.yml
index.js
src/cls-ah.js
src/cls.js
src/trace-api.js
test/plugins/common.js
test/plugins/test-trace-grpc.js
test/test-cls-ah.js
test/test-span-data.js
test/test-trace-cluster.js

Introduces a lower overhead, more correct context tracking
mechanism based on async hooks that is available when using the
trace agent on newer versions of node (>=8). To enable async 
hooks based context, set the GCLOUD_TRACE_NEW_CONTEXT environment
variable. This change is not expected to have observable behavior
difference but due to the nature of context propagation it is 
difficult to say for sure without real world testing.

Async hooks based context tracking

---

commitlint.config.js
package.json

We tried this experiment, I am not sure it is successful:
Too onerous. Unfriendly to non-collaborators. Doesn't work well with github squash and rebase workflow.
Opinions @GoogleCloudPlatform/node-team ?

get rid of commitlint

---

src/constants.ts
src/span-data.ts
src/trace-labels.ts
src/trace-span.ts
src/trace-writer.ts
src/util.ts

The style guide forbids namespaces. This commit changes `Constants` and `TraceLabels` to plain objects. Also, it removes JSDoc types.
In response to https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/559#pullrequestreview-63831472

style: change constants/trace labels to consts from namespaces; remove JSDoc types

---

index.ts
src/trace-plugin-loader.ts
src/types.d.ts
src/util.ts
test/test-config-plugins.ts
test/test-plugin-loader.ts

This change turns `trace-plugin-loader.ts` into TS.

refactor: ts conversion of plugin loader

---

package.json
src/trace-plugin-loader.ts
src/types.d.ts
src/util.ts

This change removes two TODOs since the blocking PR in DefinitelyTyped has landed.
@GoogleCloudPlatform/node-team PTAL

refactor: bump @types/node

---

package-lock.json
package.json

The semver range specified by cls@3.1.4 points to async-listener with
^0.5.0. We need at least 0.6.8 to be able to pick up the bug fix
that was affecting modules that use promise subclasses (e.g. got).

chore: update cls dependency version

---

README.md
src/plugins/plugin-restify.ts
test/plugins/fixtures/restify5/index.js
test/plugins/fixtures/restify5/package.json
test/plugins/fixtures/restify6/index.js
test/plugins/fixtures/restify6/package.json
test/plugins/test-trace-restify.ts

This change adds tracing for restify 5 and 6. Addresses #571

feat: expand restify supported version range to include v5, v6

---

config.ts
src/plugins/plugin-http.ts
src/plugins/plugin-https.ts
test/plugins/test-trace-http.ts
test/test-config-plugins.ts
tsconfig.json

Fixes #589 
Loading either `http` or `https` will cause both to be patched for tracing. This is in line with behavior in <8.9, as `https.request` used to depend on `http.request`.
The only new user-facing change is in the addition of the `https` config field: disabling causes the specific behavior of not patching `https` only if it's loaded before `http` in user-space code. It's a niche use-case so I think this is justifiable, but please let me know your thoughts.
By nature of our loader system this is uncharted territory, so feel free to give suggestions if you think there's a better approach.

src: patch https in Node 8.9 and 9.0

---

src/plugins/plugin-koa.ts
test/plugins/test-trace-koa.ts

Fixes #593
The Koa tracing plugin ignored the return value of `api.wrap`, resulting in trace context not being propagated correctly. This affects both Koa 1 and 2, but Koa 1 needs different patching logic altogether (as it relies on generator functions).

fix: propagate context in koa tracing

---

src/plugins/plugin-http.ts

Instead of restricting version range for loading https tracing, we wrap the logic in `[un]patchHttps` to be conditional on the Node version. This prevents
```
WARN:@google-cloud/trace-agent: : version v8.1.2 not supported by plugin.
```
from showing up when the version of Node being used is not 8.9.0 or 9+.

fix: prevent useless warning when patching https

---

src/plugins/plugin-http.ts
src/trace-plugin-loader.ts

In #596 I confused the condition for triggering the unwanted warning message -- this happens when no patches in a plugin fall in a given range, not when a single patch is ignored. This PR corrects for that. It's a combination of reverting #596 and changing the warn condition to be "there are patches, but none were loaded because _all_ of their supported version ranges are not satisfied". (For the https plugin, there are no patches, so the condition is false.)

fix: actually prevent warning when loading https plugin

---

package-lock.json
src/plugins/plugin-http.ts
test/plugins/test-trace-http.ts

Per node's doc, `options.port` is supposed to be a number, but
trace-agent is checking if it's a string. Update the code so we just
check if it's truthy. I think it's better because zero is not a valid
port number and it'll also work for (non-empty) strings too.

fix: options.port is supposed to be a number

---

bin/docker-trace.sh

without this, you can't repeat `docker-trace.sh start` and
`docker-trace.sh stop` because containers exist with the same names.

fix: remove docker containers on `docker-trace.sh stop`

---

src/plugins/plugin-http.ts
test/plugins/test-trace-http.ts

Otherwise, multiple listeners are attached when the client code attaches multiple `data` listeners.

fix: listenerAttached should be set to true

---

src/config.ts

Somehow I left out `projectId` from the `Config` object type definitions (probably because it doesn't have a default value)... this change adds it.

fix: add projectId to config type definitions

---

test/plugins/test-trace-http.ts

The wrong test is 'should not trace api requests'. The header name to
check should be TRACE_AGENT_REQUEST_HEADER, not
TRACE_CONTEXT_HEADER_NAME. Also the assertion should be done against the
number of spans, not against the number of traces.
Also fix the order of arguments to `assert.equal()` calls. The first
argument must be the actual result and the second the expected value.

fix: wrong test/assertion in test-trace-http

---

package-lock.json
package.json
src/span-data.ts
src/types.d.ts

`@types/node` recently introduces built-in `CallSite` and `ErrorConstructor` type definitions, so this change removes them. (The compilation will fail otherwise because the definitions are slightly incompatible.)

fix: use new node error constructor type definitions

---

package-lock.json
package.json

We use `semver.prerelease`, which is introduced in semver 5.2. This causes issues because we only necessitate that semver 5.0 or higher be installed.

fix: upgrade semver to ^5.4.1

---

package.json
src/plugins/plugin-http.ts
src/plugins/plugin-http2.ts
test/plugins/test-trace-http2.ts

Fixes #639 
The HTTP tracing plugin should not be trying to clone the HTTP request options object if it's not even clear if the request is being traced. This change ~~moves the clone to after this check has been made~~ removes the `merge` call in favor of using `setHeader` to mutate headers after `http.request` has been called.

refactor: use setHeader to set trace context header

---

package-lock.json
src/plugins/plugin-http2.ts
test/plugins/test-trace-http2.ts

Node 9.4.0 removed `rstStream...()` methods and added `close()`. Modify
the test accordingly.

fix: fix a failing http2 test in Node 9.4.0

---

.circleci/config.yml

(To be merged after v2.4.1 is released)

chore: add npm publish job to circle ci

---

src/span-data.ts
test/test-span-data.ts
test/test-trace-header-context.ts

While running a test application that was composed of multiple Node.js apps, each with tracing enabled, we found that span IDs would conflict when the multiple apps were simultaneously started, because each started their span IDs at index 1. This switches to use secure randomness for span IDs to help ensure uniqueness even when multiple Node apps are started at the same time.

Change span ID to use random bytes

---

README.md
doc/trace-api.md

doc: update broken references to source files

---

package-lock.json
package.json
src/plugins/plugin-grpc.ts
test/fixtures/plugin-fixtures.json
test/plugins/test-trace-google-gax.ts
test/plugins/test-trace-grpc.ts
test/plugins/test-trace-http2.ts
test/test-grpc-context.ts

gRPC error messages changed in 1.9... otherwise there are no changes that affect Trace Agent behavior.
To avoid having to actively bump the supported versions every time, I'm expanding the list of supported versions to all of 1.x, and in the future will push a fix if the pre-release breaks before that version comes out.

feat: expand grpc supported versions to <2

---

src/span-data.ts
src/util.ts
test/test-trace-web-frameworks.ts
test/trace.ts

This change simply moves `StackFrame` creation to utils, to make `SpanData` code simpler.

refactor: move stack frame creation to utils

---

package-lock.json
package.json
src/cls-ah.ts
src/plugins/plugin-express.ts
src/plugins/plugin-hapi.ts
src/plugins/plugin-http.ts
src/plugins/plugin-http2.ts
src/plugins/plugin-koa.ts
src/plugins/plugin-restify.ts
test/nocks.ts
test/plugins/test-trace-datastore.ts
test/test-config-credentials.ts
test/test-trace-writer.ts
test/trace.ts
test/utils.ts
tsconfig.json

The [new typedefs for @types/shimmer](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23877) is breaking but includes changes that allow us to more precisely specify types for functions being patched. This change upgrades to them and fixes a small typo that was exposed as a result.

chore: update @types/shimmer definitions

---

appveyor.yml
package-lock.json
package.json
scripts/index.ts
scripts/init-test-fixtures.ts
scripts/run-tests.ts
system-test/package.json
system-test/trace-express.js
test/test-default-ignore-ah-health.ts
test/test-trace-cluster.ts
test/test-trace-header-context.ts
test/test-trace-options-sampling.ts
test/test-trace-options.ts

The main source of flakiness in AppVeyor CI runs is timeouts stemming from `require()` calls taking up more than 4 seconds (this has been observed to be more than 10 seconds in some runs). The suspected reason for this is that we are running several databases on a VM with already-limited resources.
To circumvent this, we stop testing plugin functionality altogether, making the running of these database services entirely unnecessary. The primary reason for using AppVeyor in the first place remains to catch UNIX-specific code changes that are untested on Windows, and testing plugins may be out of that scope.
This also allows us to stop installing/caching plugin test fixtures, which also costs a significant amount of time. Some tests depend on the `express@4` fixture, but these appear to be …

test: stop testing plugin functionality on appveyor

---

src/index.ts
src/trace-writer.ts
src/util.ts
test/test-config-credentials.ts
test/test-trace-api.ts
test/test-trace-writer.ts
test/test-util.ts
test/trace.ts

This change adds a class that abstracts the "singleton" concept and uses it for the TraceWriter singleton. This makes singletons (including the future PluginLoader class) easier to mock.
I recommend looking at each commit separately

refactor: externalize singleton accessors from trace writer

---

src/index.ts
src/trace-api.ts
src/trace-writer.ts
test/test-modules-loaded-before-agent.ts

This change rewrites all log messages (except for those emitted from the Plugin Loader, which were already re-written in #686) to include class/function name, and generally be more descriptive.
Closes #675

fix: rewrite all log messages

---

src/index.ts
src/trace-plugin-loader.ts
src/util.ts
test/plugins/test-trace-generic-pool.ts
test/plugins/test-trace-grpc.ts
test/test-config-credentials.ts
test/test-config-max-label-size.ts
test/test-env-log-level.ts
test/test-env-project-id.ts
test/test-index.ts
test/test-invalid-project-id.ts
test/test-no-self-tracing.ts
test/test-trace-api.ts
test/test-trace-writer.ts
test/test-unpatch.ts
test/test-util.ts
test/trace.ts

This PR makes the flag to re-create a new instance of a singleton (or the Trace Agent as a whole) a module-private symbol `util#FORCE_NEW`. Beyond hiding this from the public API, this symbol's name now more accurately describes its general role of forcing the creation of a new singleton.
Besides replacing `forceNewAgent_` occurrences with the symbol, there are no other logical changes.

test: privatize forceNewAgent_

---

package-lock.json
package.json
src/plugins/plugin-pg.ts
src/plugins/types/index.d.ts
test/fixtures/plugin-fixtures.json
test/plugins/test-trace-pg.ts
tsconfig.json

This PR converts the PostGreSQL tracing plugin to TypeScript, makes changes to support the new API in pg@7, adds a few more tests, and changes the way `value` labels are collected.
* **chore: add pg7 to test fixtures**
* This changes a JSON file that specifies the list of modules to be installed as test fixtures, adding `pg@7`.
* **refactor: port plugin-pg to typescript**
* This converts `plugin-pg.ts` to ES6 + type annotations, and installs `pg@7` types. There should be no behavioral change.
* **fix: add support for pg 7**
* This adds a patch for `pg@7`, based on [source code](https://github.com/brianc/node-postgres) and the [upgrade guide](https://node-postgres.com/guides/upgrading).
* __Differences in a nutshell__
* In `pg@6`, an object is _always_ returned by `Client#query`, and is …

fix: add support for pg 7 changes

---

src/trace-writer.ts

Fixes #712
This PR accounts for a change in #680 in how trace labels are applied. By directly assigning fields in a spans' labels instead of using `addLabel`, we were assuming that all default labels were strings. This isn't the case, because GCP instance IDs are numbers.

fix: treat instanceId metadata as a number

---

package-lock.json
scripts/get-plugin-types.ts
src/plugins/plugin-hapi.ts
src/plugins/types/index.d.ts
test/fixtures/plugin-fixtures.json
test/test-mysql-pool.ts
test/test-trace-web-frameworks.ts
test/web-frameworks/hapi17.ts
test/web-frameworks/hapi8_16.ts

This PR adds support for tracing Hapi 17. `GCLOUD_TRACE_NEW_CONTEXT` must be set.
Fixes #601

feat: hapi 17 tracing support

---

src/index.ts
test/plugins/test-trace-http2.ts
test/test-config-plugins.ts

Fixes #719 
This change allows users to disable automatic tracing by passing a non-object value (such as `false`) for the value of `config.plugins`. It takes advantage of `extend`'s behavior of allowing non-object values to override object values, and vice versa.
Since we do not recommend disabling plugins I have not documented this feature.

fix: allow non-objects for plugins to disable automatic tracing

---

scripts/index.ts
system-test/trace-express.js

System tests fail often (but not always) because they rely on an authentication call being traced, when this is highly dependent on timing conditions (authentication needs to happen after the first call is made).

test: fix system test

---

src/index.ts
src/trace-api.ts
src/trace-writer.ts

This change causes the Trace Agent to now ignore empty string environmental variables. Formerly,
```
GCLOUD_PROJECT= node app.js
```
would initialize the `projectId` field to an empty string.
This change also fixes a few log message contents, and adds two info-level log messages for when new spans are created.

fix: fix log messages and ignore falsey env vars

---

src/cls/async-hooks.ts
test/test-cls.ts

Addresses a TODO from #708: in two different cases, a function is accepted by the tracing API; we currently do not do any restoration of context if that function throws (in other words, the newly added tests would fail). This PR addresses that.

fix: restore context when a function run with a given context throws

---

src/cls.ts
src/cls/default.ts
src/cls/null.ts
src/plugin-types.ts
src/span-data.ts
src/trace-api.ts
test/plugins/test-trace-grpc.ts
test/plugins/test-trace-http.ts
test/test-cls.ts
test/test-trace-api-none-cls.ts
test/test-trace-api.ts
test/utils.ts
tsconfig.json

Fixes #719
This PR does two things:
* In #728, a new `config.clsMechanism` option was added where, when set to `'none'`, a barebones CLS mechanism would be used where when a root span was started, it became the only possible active root span context until it was ended. This PR changes this so that root span context will _never_ be written when `clsMechanism` is set to `'none'`. Instead, the root span context always has a default value of `UNTRACED`. This affects the behavior of the custom tracing API in the following ways:
* `traceApi.runInRootSpan` will _always_ return a root span (unless disallowed by the trace policy), even if run within a function passed to another call to `runInRootSpan`.
* `traceApi.createChildSpan` will _always_ return an `UNTRACED` child span. This is because root …

feat: add rootSpan.createChildSpan and change none CLS semantics

---

src/cls/async-hooks.ts
src/cls/base.ts
test/test-cls-ah.ts
test/test-cls.ts
tsconfig.json

This PR introduces the following changes to async_hooks-based tracing:
- We now always use the `triggerId` when determining the parent `AsyncResource` _unless_ the current `AsyncResource` is of type `PROMISE`.
- We clear `this.contexts` upon disabling CLS (in practice, this happens when the Trace Agent is disabled).
- Instead of sharing the value of the current context between different async scopes, we share a reference to it instead. This way, if we set context to a different value, the change is reflected in other scopes. (This makes things more consistent but I don't think it has behavioral consequences from the perspective of the user.)
* Async scopes refer to either (1) scope in the sense of `AsyncResource#runInAsyncScope`, or (2) the function passed to either …

fix: adjust async_hooks cls behavior

---

src/cls.ts
src/index.ts
src/trace-api.ts
src/trace-plugin-loader.ts
src/trace-writer.ts
src/util.ts
test/plugins/common.ts
test/test-cls.ts
test/test-config-cls.ts
test/test-config-plugins.ts
test/test-plugin-loader.ts
test/test-trace-api.ts
test/test-trace-writer.ts
test/test-util.ts
test/trace.ts

This PR just changes methods so that a logger, if any, is always the last argument. There should be no functional changes -- this is just a self-contained part of a larger change.

refactor: make logger always last arg

---

CONTRIBUTING.md
appveyor.yml
package.json
scripts/check-install.ts

This PR makes it so that `npm run test` does everything that CI does. It also adds an install test that ensures that evaluating `require('@google-cloud/trace-agent').start()` doesn't throw an error, which could have prevented 2.8.0 from being a bogus release.
The contributing guidelines have been updated accordingly.

test: update contributing guide and add require test

---

.circleci/config.yml
appveyor.yml
package-lock.json
package.json
test/plugins/test-trace-http.ts
test/test-trace-cluster.ts
test/web-frameworks/connect.ts
test/web-frameworks/express.ts
test/web-frameworks/koa1.ts
test/web-frameworks/koa2.ts

This PR stop testing against Node 10 (which reports known failures) and also reacts to type changes introduced in `@types/node@10.0.8`.

chore: fix types and stop testing on node 10

---

test/plugins/test-trace-google-gax.ts
test/plugins/test-trace-http.ts
test/test-config-cls.ts
test/test-config-credentials.ts
test/test-config-plugins.ts
test/test-modules-loaded-before-agent.ts
test/test-span-data.ts
test/test-trace-api-none-cls.ts
test/test-trace-cluster.ts
test/test-trace-web-frameworks.ts
test/trace.ts
test/web-frameworks/koa1.ts

This test:
- Changes methods called `set*` (like `setTraceWriter`) to `set*ForTest`
- Changes references to `trace` to `testTraceModule` in tests (when it's appropriate)
Most of the diff is as a result of fixing format after these changes. I recommend `?w=1` in the URL to ignore whitespace changes.

test: make it clear that some methods are test-only

---

README.md

At some point we moved from Travis and Coveralls to Circle and Codecov, respectively. This PR updates the status badges that are now out of date.

doc: update status badges

---

src/plugin-types.ts
src/span-data.ts
test/test-span-data.ts

Fixes #456
This PR adds an option to specify a time when a given span should be ended.

feat: allow timestamps to be passed to endSpan

---

src/cls.ts
src/cls/singular.ts
src/config.ts
test/test-cls.ts
test/test-config-cls.ts

This PR adds a `'singular'` CLS option, which is meant to be used in a serverless environment where a single request is being served per instance.

feat: add singular cls option

---

src/cls.ts
src/constants.ts
src/plugin-types.ts
src/plugins/plugin-grpc.ts
src/plugins/plugin-pg.ts
src/span-data.ts
src/trace-api.ts
test/plugins/common.ts
test/plugins/test-trace-grpc.ts
test/test-cls.ts
test/test-index.ts
test/test-span-data.ts
test/test-trace-api-none-cls.ts
test/test-trace-api.ts
test/utils.ts

This PR addresses two TODOs:
- `SpanData` should be named `Span` for the public API (this is suggested by the OpenCensus specification, and avoids name collisions)
- An outstanding TODO was to be done when "null spans" were implemented (#680)

refactor: address TODOs related to spans

---

test/plugins/test-trace-http2.ts

8.11.2 contains backported changes to the http2 API from Node 9. https://nodejs.org/docs/latest-v8.x/api/http2.html

test: fixup for node 8.11.2

---

src/config.ts
src/index.ts
src/trace-plugin-loader.ts
src/tracing.ts
src/util.ts
test/test-plugin-loader.ts

~~This PR makes `async_hooks`-based Tracing the default option for tracing using Node 8+. To go back to using `async-listener` (via `continuation-local-storage`), new `config.clsMechanism` options are accepted: `async-listener` (and `async-hooks`).~~
This PR provides two new possible values for `config.clsMechanism`: `async-listener` and `async-hooks`.
Because context tracking is now specified as a config option rather than strictly as an environmental variable, a fair bit of refactoring is needed to support conditionally loading `continuation-local-storage` as late as possible. The constraints to satisfy are as following:
- `continuation-local-storage` needs to be loaded as early as possible, and definitely before any modules that do I/O.
- `continuation-local-storage` must be loaded …

 feat: add options to set the cls mechanism to async-hooks or async-listener

---

package.json

[Release Notes](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/releases/tag/untagged-64026924b81c2bbbf765)

chore: 2.9.0 release proposal

---

package.json

[Release Notes](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/releases/tag/untagged-1cbd299a868fd04b94f9)

chore: 2.10.0 release proposal

---

src/plugins/plugin-http.ts
test/plugins/test-trace-http.ts

Fixes #763
This PR fixes a bug where our HTTP instrumentation fails if `Expect` is added as an outgoing header. This is because we normally inject a trace context header for a request as part of our HTTP instrumentation, but Node has a special case where it prohibits additional headers if the `Expect` header is detected. See: https://github.com/nodejs/node/blob/v7.10.1/lib/_http_outgoing.js#L323
To fix this, I brought back the old "slower" way of injecting trace context headers that was removed in #643, but only if the `Expect` header is detected.
I also added a test that fails without the source change.

fix: inject context http headers early if expect header exists

---

test/test-trace-api.ts
tsconfig.json

This PR converts `test-trace-api.ts` to TS, and is a soft pre-req for a future change to upgrade to `@google-cloud/common@0.19`.
Tests have been refactored to use new test classes and features. A few tests were removed:
`constants` -- change detector tests that are not needed.
`should expose the same interface regardless of state` -- relic of old implementation of Trace API where the disabling the agent changed its prototype. TS now guarantees this.
`should add labels to spans` -- already tested in other tests in this file.
Also, in general `Span` objects are not converted to `SpanData` objects anymore (former -- exposed to users, latter -- used internally, containing fields like `spanId` etc); instead, we simply write the spans with a fake Trace Writer and then query them later.

test: modernize test-trace-api

---

.circleci/config.yml
scripts/init-test-fixtures.ts
test/fixtures/plugin-fixtures.json
test/plugins/test-trace-grpc.ts
test/test-grpc-context.ts

This change enables Node 10 CI. It also modifies `init-test-fixtures` to re-install gRPC binaries if there is a module version mismatch, and allows `engines.node` in `plugin-fixtures.json` to dictate whether the fixture is actually installed (at this time, there is only gRPC 1.6). The former doesn't affect CI, it is purely for developer convenience when switching between Node versions locally.

chore: re-enable node 10 ci and modify init-test-fixtures

---

src/cls.ts
src/plugin-types.ts
src/trace-api.ts
src/trace-writer.ts
test/test-index.ts
test/test-trace-api.ts
test/test-trace-uncaught-exception.ts
test/test-trace-writer.ts

This PR adds two methods on the TraceAgent class, `getProjectId` and `getCurrentRootSpan`, which should supercede `getWriterProjectId` and `getCurrentContextId` respectively. It also uses `TraceWriter#projectId` instead of `TraceWriter#config.projectId` to store the retrieved project ID, because this is already the behavior of `Service`. In practice, this fixes a regression with `getProjectId`.

feat: add getProjectId and getCurrentRootSpan

---

.circleci/config.yml
CONTRIBUTING.md
README.md
appveyor.yml
src/config.ts
src/index.ts
system-test/trace-express.js
test/plugins/common.ts
test/test-config-cls.ts

Fixes #566
This PR removes references to `GCLOUD_TRACE_NEW_CONTEXT`. Code that depend on its value now behave as if it were always `true`.
This change makes `async_hooks`-based tracing the default behavior in Node 8+.

feat: support tracing for untranspiled async/await in Node 8+

---

.circleci/config.yml
README.md
appveyor.yml
package.json

BREAKING CHANGE: This change drops support for Node 4 and 9.
r-i-t-m needs to be fixed at 2.2.1. Tracking this at #779.
Actually, I do not want this to land yet.

chore: drop support for node 4 and 9

---

src/constants.ts
src/plugins/plugin-grpc.ts
test/plugins/test-trace-grpc.ts

BREAKING CHANGE: The change in distributed trace context propagation across gRPC is not backwards-compatible. In other words, distributed tracing will not work between two Node instances communicating using gRPC with v2 and v3 of the Trace Agent, respectively.
Trace context can now be propagated thru gRPC with the `'grpc-trace-bin'` key, and a binary-encoded value.

feat: use well-known format for propagating trace context thru grpc

---

README.md
doc/trace-api.md
src/constants.ts
src/index.ts
src/plugin-types.ts
src/plugins/plugin-connect.ts
src/plugins/plugin-express.ts
src/plugins/plugin-grpc.ts
src/plugins/plugin-hapi.ts
src/plugins/plugin-http.ts
src/plugins/plugin-http2.ts
src/plugins/plugin-koa.ts
src/plugins/plugin-restify.ts
src/trace-api.ts
src/trace-plugin-loader.ts
src/tracing.ts
test/plugins/common.ts
test/test-agent-stopped.ts
test/test-index.ts
test/test-trace-api-none-cls.ts
test/test-trace-api.ts
test/trace.ts

BREAKING CHANGE: `TraceAgent` has been renamed to `Tracer`. In plugins, `Patch` has been renamed `Monkeypatch`, and `Patch` is now `Monkeypatch|Intercept` (this is a rename of `Instrumentation`). There are no user-visible JS changes.
`TraceAgent` is a misnomer since the module as a whole is the "agent", not the object that is returned when the Trace Agent is started. (This is already reflected in the docs, where it has been called `TraceApi`). This change makes things consistent so it is called `Tracer` everywhere.
The one implementation of `TraceAgent` (which was also called `TraceAgent`) is now `StackdriverTracer`. This object is never constructed by the user, so this is a no-op change for JS users.
A couple of unused imports have also been removed.

feat: rename TraceAgent/TraceApi to Tracer

---

test/test-util.ts

deepEqual is deprecated. Use deepStrictEqual instead

chore: assert.deelEqual => assert.deepStrictEqual

---

package.json

chore: pin @types/node at 10.7

---

.circleci/config.yml

CI always runs into this error:
```
Restoring Cache
Error computing cache key: template: cacheKey:1:93: executing "cacheKey" at <checksum "package-lo...>: error calling checksum: open /root/project/package-lock.json: no such file or directory
```
Deleting it since it doesn't work anyways.

fix: delete cache as it is not working anyways

---

package.json
src/trace-writer.ts
test/test-trace-writer.ts

Use teenyRequest instead of request. This saves 900 ms at
startup time.
Improve load time from 1500 ms to 650 ms. 
Before `request`:
After with `teenyRequest`:

feat: use small HTTP dependency

---

src/plugins/plugin-grpc.ts
test/plugins/common.ts
test/plugins/test-trace-grpc.ts

Fixes #873
Since gRPC 1.7 the original, capitalized name of a method is a synonym for the lower-cased version. We didn't trace these methods before, so this PR enables tracing for those methods.

fix: enable tracing on original client method names

---

src/logger.ts

The new `Logger` class doesn't include `ERROR`/`WARN` etc to allow users to distinguish log levels... this PR fixes this.

fix: add log level to logger prefix

---

src/config.ts
src/trace-api.ts
test/plugins/common.ts
test/test-plugin-loader.ts
test/test-trace-api.ts

Given that the scenario #838 is likely caused by context confusion on long-running requests, this warning should help us determine whether a memory leak is due to an intrinsic design detail to the agent, or context confusion. Emitting this warning is a clear sign of the latter (the remedy would be to identify the userspace queueing mechanism that breaks context, and patch it/request that it support async resources).

feat: emit an error log on potential memory leak scenario

---

src/trace-api.ts
src/tracing-policy.ts
test/plugins/common.ts
test/plugins/test-trace-grpc.ts
test/test-trace-api.ts
test/test-trace-policy.ts
tsconfig.json

This change removes two TODOs from the codebase related the Trace Policy, namely:
- Turn `TracePolicy` into a class
- Privatize `StackdriverTracer.policy`

refactor: address trace policy TODOs

---

src/cls/async-hooks.ts
test/test-cls-ah.ts

Most Promise async resources require a separate `promiseResolve` event listener. See the inline comments for more details.

fix: avoid memory leaks due to undisposed promise resources

---

src/span-data.ts
src/trace-writer.ts
src/tracing.ts
test/plugins/common.ts
test/test-span-data.ts
test/test-trace-api.ts
test/test-trace-uncaught-exception.ts
test/test-trace-writer.ts
test/trace.ts

This PR contains three changes (in separate commits) that improve the TraceWriter API, narrowing down its trace-writing surface to _just_ `writeTraces` and promisifying the initialization step. This should make #794 easier to fix.

refactor: improve internal TraceWriter API

---

test/test-trace-cluster.ts

Fixes #659
When the TODO in question was written (see diff), there was a failure that was attributed to how `cluster` interacted with `async_hooks`. After doing some investigation, I realized that the fault actually lies in [the way CLS was being implemented on top of `async_hooks` at the time](https://github.com/googleapis/cloud-trace-nodejs/blob/v2.8.0/src/cls/async-hooks.ts#L47-L59). Because the `after` hook isn't being called, context would leak to the next entered resource if the next entered resource didn't already have a context associated with it.
This has already been fixed in v2.9.0, specifically #734, which obviated `before`/`after` hooks entirely. So this test should work as it did before.

test: remove cluster test todo

---

samples/.gitignore
samples/README.md
samples/app.js
samples/app.yaml
samples/package.json
samples/snippets.js

Fixes #909
This sample app was taken directly from https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/trace. I modified the README (to fix broken links, and also to remove sections that seemed copy-pasted from other READMEs) and package.json (to update the Trace Agent version).

chore: add a sample app

---

README.md

Was pointing to `mysql2` instead of `pg`

doc: Fix pg npm link

---

README.md
src/config.ts
src/plugin-types.ts
src/plugins/plugin-connect.ts
src/plugins/plugin-express.ts
src/plugins/plugin-hapi.ts
src/plugins/plugin-koa.ts
src/plugins/plugin-restify.ts
src/trace-api.ts
src/tracing-policy.ts
test/plugins/common.ts
test/test-plugin-loader.ts
test/test-trace-api.ts
test/test-trace-policy.ts
test/test-trace-web-frameworks.ts

pull request for: https://github.com/googleapis/cloud-trace-nodejs/issues/919

add ignoreMethods option

---

package.json

[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-5e56392ca8cc1c15034a)

chore: 3.5.0 release proposal

---

package.json
src/plugins/plugin-grpc.ts
test/test-grpc-async-handler.ts
test/test-grpc-proto.d.ts
tsconfig.json

Fixes #952
`plugin-grpc.ts` is best viewed with `?w=1`.

fix: wrap gRPC server async handlers

---

package.json

[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-6fcbc3540dc6adf05634)

chore: 3.5.1 release proposal

---

src/plugins/plugin-pg.ts
test/plugins/test-trace-pg.ts

Test failures in PR #913 (support child spans with tail latencies) exposes an issue with the instrumentation code for Postgres, where child spans were not being closed if a generic `Submittable` is used in lieu of a `Query`. This PR fixes that.

fix: end child spans correctly in pg

---

src/trace-api.ts

This will change log messages like this from:
```
[JS] @google-cloud/trace-agent DEBUG TraceApi#createChildSpan: [undefined] Created child span [doSomething()]
[JS] @google-cloud/trace-agent DEBUG TraceApi#createChildSpan: [undefined] Created child span [doSomething() -> browserStart]
```
To this:
```
[JS] @google-cloud/trace-agent DEBUG TraceApi#createChildSpan: [noPluginName] Created child span [doSomething()]
[JS] @google-cloud/trace-agent DEBUG TraceApi#createChildSpan: [noPluginName] Created child span [doSomething() -> browserStart]
```

Output `'noPluginName'` in trace-api log messages where pluginName is undefined

---

package.json

[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-e0651471b9f47020551c)

chore: 3.5.2 release proposal

---

test/test-trace-hapi-tails.ts
test/test-trace-web-frameworks.ts
test/web-frameworks/base.ts
test/web-frameworks/connect.ts
test/web-frameworks/express.ts
test/web-frameworks/hapi17.ts
test/web-frameworks/hapi8_16.ts
test/web-frameworks/koa1.ts
test/web-frameworks/koa2.ts
test/web-frameworks/restify.ts
tsconfig.json

Fixes #382
Since child spans are now allowed to track tail latencies, this PR adds a test to ensure that users of the Hapi tails API (up to v16, but also including the more general recommended mechanism in the [v17 release notes](https://github.com/hapijs/hapi/issues/3658) under "Misc") can observe these child spans.
Note that child spans still cannot begin _after_ a root span has ended.

test: test hapi tails

---

test/test-grpc-context.ts

We should stop making a request to `http://www.google.com/` in our unit test.

test: don't make network request in gRPC context test

---

package.json

[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-aa9f39d9e9a86e0db90b)

chore: 3.6.0 release proposal

---

src/plugins/plugin-http.ts
test/plugins/test-trace-http.ts

It's possible for `setHeader` to throw if an outgoing request was created with a header `Expect` but not capitalized exactly that way. This change makes checking for the `expect` header a little more robust, and also swallows an error that would be thrown for further unexpected capitalizations.
It's possible that `hasExpectHeader` can either (1) stay the same or (2) be even more robust and actually iterate through all header keys to do a case-insensitive check. I'm definitely OK with the first option, the second option might have too much overhead to accomadate for a rare issue.

fix: don't let trace context injection throw

---

package.json
src/config.ts
src/plugins/plugin-mongoose.ts
test/plugins/test-trace-mongoose-async-await.ts
tsconfig.json

Fixes #1000
The problem occurs because `Query#exec` (which makes the MongoDB API call) occurs within the body of a userspace `then` call, which has no context when `await`ed. To remedy this, we patch new `Query` objects so that `exec` has the same context as where the `Query` was created. This assumes that we want context at the API call to be the same as the place where `Query` was constructed. As much (if not all) of the Mongoose read APIs create and execute the `Query` objects in a single function call, I believe this to be a safe assumption.

fix: support tracing awaited mongoose queries

---

README.md

Hello, the docs for ignoreUrls have a mysterious hash that me and my team think may be a mistake in the docs. I have updated it to prevent others from having the same discussion.
... or maybe is has some mysterious power we can't figure out?

remove the hash from the ignoreUrls in docs

---

package.json

[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-2d501a08e592789b8f1c)

chore: 3.6.1 release proposal

---

package.json
src/util.ts

This produces nice call stacks that display line and column numbers from transpiled TypeScript, Coffee Script, etc source files like this:
```
Callstack
runInSpan (/app/src/trace-util.ts:129:30)
runDispatcherInTrace [as runDispatcherInTrace] (/app/src/trace-util.ts:167:18)
source.asCallback (/app/src/dispatcher/simpleDispatcher.ts:57:29)
dispatchMessage (/app/src/source/natsSource.ts:141:9)
trace_util_1.runInSpan (/app/src/source/natsSource.ts:74:19)
that.runWithContext (/app/node_modules/@google-cloud/trace-agent/build/src/cls/async-hooks.js:143:49)
runWithContext [as runWithContext] (/app/node_modules/@google-cloud/trace-agent/build/src/cls/async-hooks.js:121:20)
contextWrapper (/app/node_modules/@google-cloud/trace-agent/build/src/cls/async-hooks.js:143:25) …
```

feat: use souce-map-support wrapCallSite to apply source maps to call stacks

---

test/fixtures/source-maps-test/external-source-map.js
test/fixtures/source-maps-test/external-source-map.js.map
test/fixtures/source-maps-test/external-source-map.ts
test/fixtures/source-maps-test/inline-source-map.js
test/fixtures/source-maps-test/inline-source-map.ts
test/fixtures/source-maps-test/inline-sources.js
test/fixtures/source-maps-test/no-source-map.js
test/test-span-data.ts

test: test source map support for stack traces

---

src/tracing-policy.ts

The `URLFilter` and `MethodsFilter` implementations are side-effect
free, and are safe to run in any order. However, `sampler.shouldTrace`
is not, a result of `true` from it has the side effect of altering the
trace window.
Expected behavior
=================
RPCs to a filtered URL or method should not affect sample rates of
unfiltered URLs or methods.
Actual behavior
===============
A high rate of RPCs relative to the sample rate that are filtered causes
the actual sampling to be biased and below the expected rate.
Suppose that external RPCs occur at the same frequency as interval as
health checks: the resulting sample rate will be approximately 1/2 the
specified rate, because it will be (about) a coin flip whether the first
request in an interval is a healthcheck or a valid RPC.
If the …

fix: Prevent filtered traces from biasing the sample rate

---

test/test-plugins-sample-warning.ts

Like #970, this changes a test to make a request to a local endpoint rather than `google.com`.

test: stop querying google.com

---

.circleci/config.yml

We've already "dropped" support for Node 6 in #1011, this allows us to start acting on that.

chore: stop testing on node 6 in ci

---

package.json
src/config.ts
src/index.ts
src/plugin-types.ts
src/plugins/plugin-connect.ts
src/plugins/plugin-express.ts
src/plugins/plugin-grpc.ts
src/plugins/plugin-hapi.ts
src/plugins/plugin-http.ts
src/plugins/plugin-http2.ts
src/plugins/plugin-koa.ts
src/plugins/plugin-restify.ts
src/span-data.ts
src/trace-api.ts
src/trace-plugin-loader.ts
src/tracing.ts
src/util.ts
test/plugins/common.ts
test/plugins/test-trace-grpc.ts
test/test-config-plugins.ts
test/test-index.ts
test/test-plugin-loader.ts
test/test-span-data.ts
test/test-trace-api.ts
test/utils.ts

Fixes #949, supercedes #950
With this change:
- Trace context header extraction and injection has been abstracted out of plugins and now exists in the `Tracer`.
- Its default underlying implementation is [`@opencensus/propagation-stackdriver`](https://www.npmjs.com/package/@opencensus/propagation-stackdriver) (behavior should match what the plugins do currently)
- APIs that make an assumption about trace context format have been __removed__ or __changed__. In particular (this is a __semver-major__ change):
- `Tracer#traceContextUtils` no longer has methods for encoding and decoding trace context as a string.
- The following APIs accept/return `TraceContext` objects instead of strings:
- `Tracer#getResponseTraceContext`
- `Tracer#createRootSpan`
- `Span#getTraceContext`
- Users can now set …

feat!: support user-specified context header propagation

---

.circleci/config.yml
test/fixtures/plugin-fixtures.json
test/plugins/test-trace-http2.ts
test/plugins/test-trace-redis.ts
test/test-cls-ah.ts

This change adds Node 12 as a Circle CI job, and de-facto adds support for Node 12. The following changes need to be made in the process:
* Because `hiredis` doesn't seem to build on Node 12 I've also opted to not test it on Node 12. I recommend viewing [files changed with `?w=1`](https://github.com/googleapis/cloud-trace-nodejs/pull/1002/files?w=1) to see a more illustrative diff. (Also see [`describeInterop` implementation notes](https://github.com/googleapis/cloud-trace-nodejs/blob/v3.6.1/test/utils.ts#L186-L200))
* References to Promises no longer exist on `PROMISE`-type async resources, so I've amended a test to count an expected number of async hook invocations rather than compare exact values retrieved from those async hook invocations.
* Node 12 appears to have a bug where async …

chore: add node 12 ci job

---

src/cls.ts
src/constants.ts
src/span-data.ts
src/trace-api.ts
test/test-cls.ts
test/test-default-ignore-ah-health.ts
test/test-index.ts
test/test-trace-api-none-cls.ts
test/test-trace-api.ts

Fixes #1025
We already store untraced requests (via a single object representing ALL untraced requests) in CLS, this changes it so that these objects also have a trace ID (and span ID, though not sure if it is useful).

fix!: always assign a trace ID to each request

---

package.json

[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-355cbcdd90f787ea50f1)

chore: 4.0.0 release proposal

---

README.md

We no longer support any versions of Node where `async_hooks` isn't present.

doc: remove references to old versions of Node in README.md

---

src/index.ts
src/trace-writer.ts
src/tracing.ts
test/test-config-priority.ts
test/test-config.ts
test/test-trace-api.ts
test/test-trace-writer.ts
test/trace.ts

fix: copy credentials in internal config

---

scripts/get-plugin-types.ts

`.` appears not to match `\r` in a regex, so `get-plugin-types` won't work on Windows if git is configured to use CRLFs.
__Note__: Kokoro CI results can be ignored

build: fix `npm run get-plugin-types` on windows

---

scripts/index.ts

These tests have been added since `TRACE_TEST_EXCLUDE_INTEGRATION` has last been put into use (on Appveyor). This change is needed for CI environments where spinning up docker containers is difficult.
__Note__: Kokoro CI results can be ignored

build: mark some new tests as integration tests

---

test/plugins/test-trace-mongoose-async-await.ts

This PR fixes a typecheck error when using `@types/mongoose@5.5.8`.

test: fix type issue in mongoose test

---

src/tracing.ts
test/test-modules-loaded-before-agent.ts

fix: warn if tracing might not work instead of err

---

doc/trace-api.md

Update link to config file in docs

---

package.json
src/tracing.ts
test/fixtures/plugin-fixtures.json
test/plugins/test-trace-http.ts
test/plugins/test-trace-node-fetch.ts
test/web-frameworks/express-secure.ts
tsconfig.json

Requests from `node-fetch` currently might not get traced, because we use it in the Trace Agent (for authentication). Because it's loaded in the Trace Agent before we set up monkeypatching, we don't have a way to hook into its require of `http` or `https`. Therefore, for `http`, if it's the only module to be included that would require `http`, then `http` will never get patched, and HTTP requests will never get traced. The same is independently true of `https`. (Common HTTP frameworks will typically require `http`, alleviating this problem for HTTP requests. However, in a Cloud Functions environment, this might not apply, as even the HTTP framework is required before the Trace Agent has a chance to set up monkeypatching.)
We address this simply by requiring `http` and `https` when the …

fix: force http and https clients to be patched

---

test/test-trace-web-frameworks.ts

The aborted span test is the # 1 cause of flakes. By waiting 1000ms instead of 600ms, I hope this will reduce the number of flaky results.

test: relax aborted span test

---

src/config.ts
src/plugins/plugin-hapi.ts
test/fixtures/plugin-fixtures.json
test/test-config-plugins.ts
test/test-trace-web-frameworks.ts
test/web-frameworks/hapi17.ts

Fixes #1107
This PR adds support for hapi 18 (now `@hapi/hapi`).

feat: support @hapi/hapi

---

.circleci/config.yml

Fixes #1119
This allows us to discover breakages due to external changes from nightly runs, and also should make non-nightly tests run faster.

chore: invalidate circleci cache nightly; cache node_modules again

---

package.json
scripts/utils.ts
src/plugins/plugin-http.ts
src/plugins/plugin-koa.ts
test/plugins/test-trace-http.ts
test/test-cls-ah.ts

This PR adds support for a new signature of `http.request` in Node 10.9+. It also unpins `@types/node`.

fix: unpin @types/node and account for new http.request signatures

---

src/config.ts
src/plugins/plugin-mongodb.ts
test/fixtures/plugin-fixtures.json
test/plugins/test-trace-mongoose.ts

Fixes #1123
Note: We aren't officially adding support for the `mongodb` npm module (tracing might work, but it almost might not), only extending our support for `mongoose`.

fix: tracing not working in mongoose 3.3+

---

test/test-trace-hapi-tails.ts
test/web-frameworks/hapi17.ts
test/web-frameworks/hapi8_16.ts

New TS definitions for `events` doesn't allow anonymous subclasses of `EventEmitter` (or something like that), so compilation broke a little. This PR fixes that.

test: don't override event emitters

---

system-test/package.json

got@10 doesn't support Node 8, and also makes a breaking API change which requires an amendment to our system tests (this isn't a bad or breaking change for us, but for now, we will postpone making a change in our tests).

chore: downgrade to got@9 in system tests

---

src/plugins/plugin-http.ts
test/plugins/test-trace-http.ts

In Node 10 and above and libraries which use the `request(url, options, cb?)` overload of the request function such as `got` 10.x, request tracing fails.
Environment details
-------------------
- OS: any
- Node.js version: 10.x
- npm version: 6.x
- `@google-cloud/trace-agent` version: 4.5.2
Steps to reproduce
------------------
1. Use `got` version `10.x` or manually invoke a request with a separate URL and options argument
2. In a root span, try to do a `got.post` or any other request as above and log the `x-cloud-trace-header` in the server receiving the request
3. Observe that the request isn't traced and the trace header is absent
Bug
---
The bug is in three parts:
1. If condition filters out valid requests:
https://github.com/googleapis/cloud-trace-nodejs/blob/ac7e886c178ca9c34502e9ba …

fix: handle Node 10 style http requests

---

.github/workflows/ci.yaml

Workaround for issue discussed here: https://github.com/nodejs/node/issues/33254
Should be possible to revert once Node.js 12.16.3 is released.

Change Windows CI to use Node.js 10

---

samples/app.js

App sample has error: TypeError: The `GET` method cannot be used with a body
This pull request is to update the body to an json response option
Fixes #1246 🦕

fix: sample app TypeError

---

package.json

Releases are now automated, _also based on Conventional Commits_, but we should no longer need `standard-version` (which did the same thing when run manually.

chore(deps): we no longer use standard-version for releases
