googleapis/cloud-trace-nodejs

.travis.yml, bin/run-test.sh, package.json, pre-push
=> Fix Travis config and allow hook tests to be run on Travis

lib/hooks/index.js, test/standalone/test-index.js
Fixes: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/1
=> allow agent to be restarted

index.js, lib/trace-agent.js, package.json
=> Add version check for >=0.12

index.js, test/standalone/test-agent-metadata.js, test/standalone/test-index.js
Fixes: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/2
=> improve handling of config.projectId

index.js, lib/constants.js, lib/hooks/core/hook-http.js, lib/hooks/userspace/hook-express.js, lib/hooks/userspace/hook-hapi.js, lib/hooks/userspace/hook-restify.js, lib/span-data.js, lib/trace-agent.js, lib/trace-writer.js, lib/utils.js, test/standalone/test-agent-metadata.js, test/test-trace-agent.js, test/test-utils.js
=> Some cleanups, and fix for span warnings on own requests

test/hooks/test-trace-mongodb.js, test/hooks/test-trace-redis.js
=> Don't exit process if mongo/redis isn't present

package.json, test/standalone/test-agent-metadata.js, test/standalone/test-trace-writer.js
=> Improved testing coverage for trace writer

test/hooks/test-trace-mongodb.js
=> Fixed mongo test to hit find path with no parent span

lib/hooks/core/hook-http.js, lib/span-data.js, lib/trace-agent.js, test/test-span-data.js, test/test-trace-agent.js
=> adding context to headers is now part of the agent's private api

index.js, test/standalone/test-index.js
This issue has bitten me for the last time. @ofrobots PTAL
=> accept numeric project ids in config

index.js, package.json
=> updated common utils to 0.2.0

lib/hooks/core/hook-http.js, lib/trace-labels.js, test/hooks/test-trace-http.js
=> Add non-http error labels to http requests

.travis.yml
Not quite sure if Travis is ready yet, but this PR should find out.
=> start testing against Node.js 4.x

lib/span-data.js, test/test-span-data.js
=> Implement support for structured stack traces

package.json
=> added respository to package definition

bin/run-bump.sh
=> Push tags created by npm version in bump script

config.js
=> GCLOUD_TRACE_DISABLE env var no longer ignored

lib/hooks/core/hook-http.js, lib/hooks/index.js, lib/hooks/userspace/hook-express.js, lib/hooks/userspace/hook-hapi.js, lib/hooks/userspace/hook-mongodb-core.js, lib/hooks/userspace/hook-redis.js, lib/hooks/userspace/hook-restify.js, lib/span-data.js, lib/trace-agent.js, lib/trace-writer.js
Info level logging will now give more information on patching lifecycle. Also improves logging around ending spans and warns users if a module that we patch is already loaded when the agent starts up.
=> Expanded logging coverage

config.js, lib/hooks/userspace/hook-express.js, lib/hooks/userspace/hook-hapi.js, lib/hooks/userspace/hook-restify.js, lib/span-data.js, lib/trace-agent.js, lib/trace-span.js, lib/trace-writer.js, lib/tracing-policy.js, test/hooks/common.js, test/standalone/test-index.js, test/standalone/test-trace-writer.js, test/test-span-data.js, test/test-trace-agent.js, test/test-trace-policy.js
=> A more complete solution for sampling

config.js, index.js, lib/trace-labels.js, lib/trace-writer.js, package.json, test/hooks/test-hooks-index.js, test/non-interference/http-e2e.js, test/standalone/test-agent-metadata.js
This depends on the changes in
GoogleCloudPlatform/cloud-diagnostics-common-nodejs#10
Fixes #100
=> Report GCE instance information as labels on spans

lib/constants.js, lib/trace-labels.js, lib/trace-writer.js
=> Reports agent version as a label on every span

index.js, lib/hooks/index.js, lib/tracing-policy.js, test/hooks/test-trace-mongodb.js, test/hooks/test-trace-redis.js, test/non-interference/restify-e2e.js, test/standalone/test-agent-metadata.js
Some PRs were submitted without LGTM while reviewers were away last
week. This PR fixes retroactive review comments for #102, #105, and #106.
=> Cleanup for submitted PRs

lib/trace-agent.js, test/standalone/test-ignore-url-express.js
=> Bug fix for filtering ignored urls

lib/hooks/userspace/hook-express.js, lib/hooks/userspace/hook-hapi.js, lib/hooks/userspace/hook-restify.js, lib/trace-labels.js, test/hooks/fixtures/redis2/package.json, test/hooks/test-trace-express.js, test/hooks/test-trace-hapi.js, test/hooks/test-trace-restify.js
=> Report source IP on spans

config.js, test/hooks/common.js, test/standalone/test-ignore-url-express.js, test/standalone/test-trace-writer.js, test/test-span-data.js
Chose a rate of 10 traces per second.
Fixes #125
=> Enable sampling by default

config.js, lib/tracing-policy.js
Setting to 0 gathers all traces
Fixes #127
=> SamplingRate can be set to 0

.travis.yml
=> Run travis tests against node 5

index.js, test/fixtures/test-config.js, test/standalone/test-config-priority.js
=> Read config from an enviroment variable

.travis.yml, lib/hooks/index.js, lib/hooks/userspace/hook-mysql.js, lib/hooks/userspace/hook-redis.js, test/hooks/fixtures/mysql2/index.js, test/hooks/fixtures/mysql2/package.json, test/hooks/test-trace-mysql.js, test/standalone/test-hooks-sample-warning.js
=> Tracing support for mysql

config.js
=> Capture 10 stack frames on traces by default

.travis.yml, test/hooks/fixtures/redis2-hiredis0.4/index.js, test/hooks/fixtures/redis2-hiredis0.4/package.json, test/hooks/test-trace-redis.js
=> Test redis using hiredis parser

.travis.yml, lib/span-data.js
* remove node 2 builds.
* remove a useless log message
=> Minor changes

lib/hooks/core/hook-http.js, lib/trace-agent.js, test/test-constants.js, test/test-trace-agent.js
=> Define header to identify our own requests

index.js, lib/hooks/core/hook-http.js, lib/trace-agent.js, lib/trace-writer.js, test/standalone/test-no-self-tracing.js, test/test-trace-agent.js
=> Stop tracing http requests made by agent

lib/trace-agent.js, test/test-trace-agent.js
=> Parsed spanids should have type number

config.js, lib/hooks/userspace/hook-mongodb-core.js, lib/util.js, test/hooks/common.js, test/test-util.js
This information is only reported if the `enhancedReporting` flag is
set.
Fixes #97.
=> Report query and result information for mongodb

lib/hooks/userspace/hook-redis.js, test/hooks/test-trace-redis.js
=> Enable enhanced database reporting for redis

lib/hooks/userspace/hook-mysql.js, test/hooks/test-trace-mysql.js
=> Enable enhanced database reporting for mysql

index.js, test/standalone/test-index.js
=> Agent starts automatically and is on global

index.js, test/fixtures/preloaded-agent.js, test/standalone/test-preloaded-agent.js
=> agent should start automatically when --require'd

index.js, lib/trace-labels.js, lib/trace-writer.js, test/standalone/test-agent-metadata.js
This is needed in addition to the module_name and module_version labels.
=> add app/version label aswell

lib/hooks/userspace/hook-express.js
=> Do not modify methods in the module cache

lib/hooks/index.js
=> remove incorrect comment

test/standalone/test-no-self-tracing.js
Travis intermittently fails on these.
@matthewloring PTAL.
=> increase test-no-self-tracing timeout

index.js, test/fixtures/test-config.json, test/standalone/test-config-json.js, test/standalone/test-config-relative-path.js
=> Support relative config file paths from cwd

README.md, config.js, index.js, lib/hooks/index.js
=> Warn about preloaded modules loaded before trace

lib/constants.js, test/standalone/test-trace-header-context.js, test/test-constants.js
=> Handle headers as lowercase

README.md
=> Document sampling and publishing behavior

lib/hooks/index.js, lib/hooks/userspace/hook-grpc.js, test/fixtures/test.proto, test/hooks/fixtures/grpc0.13/index.js, test/hooks/fixtures/grpc0.13/package.json, test/standalone/test-grpc-context.js
=> Experimental support for grpc tracing

lib/hooks/userspace/hook-express.js, lib/hooks/userspace/hook-hapi.js, lib/hooks/userspace/hook-koa.js, lib/hooks/userspace/hook-restify.js, lib/span-data.js, lib/trace-agent.js, lib/trace-span.js, test/hooks/test-trace-express.js, test/hooks/test-trace-hapi.js, test/hooks/test-trace-mongodb.js, test/hooks/test-trace-mysql.js, test/hooks/test-trace-redis.js, test/hooks/test-trace-restify.js, test/standalone/test-trace-koa.js, test/test-span-data.js
=> Remove trace span functions from stack traces

config.js, index.js, lib/trace-agent.js, test/standalone/test-trace-uncaught-exception.js
=> Attempt to publish traces on unhandled exception

src/trace-plugin-loader.js, test/test-plugin-loader.js
This change makes the `unpatch` field of a patch object functional. The plugin loader unpatches upon a call to `pluginLoader.deactivate()`. There's a test (at the bottom of `test/test-plugin-loader.js`) that checks this.
In addition, I've removed the two-level storage of plugins (again), since it's not possible for a module at a single path to have more than one version -- keying on module path should be sufficient for storing patches for different versions of the same module, as it was in `hooks/index.js`.
This causes a slight complication in a test that ensured that two different versions of the same module could both be loaded. The current test harness is incapable of testing this, so I've left it as a TODO for now (though I do have an attempt at …
=> Plugin API: Add unpatching

README.md, doc/plugin-guide.md, doc/trace-api.md
=> Trace API and Plugin Developer Docs

CHANGELOG.md, package.json
This also updates the name of the module to @google-cloud/trace-agent.
=> 1.0.0-rc1 Release Proposal

src/plugins/plugin-http.js, test/plugins/test-trace-http.js
Responses returned by http#request are yielded in paused mode. By
attaching a 'data' listener to the request the http instrumentation was
switching the stream to flowing mode which could cause the request to
drain before the calling framework had a chance to attach their own
listeners.
Fixes #437
=> Ensure http response streams are paused

package.json
See also https://github.com/kjin/google-cloud-counters
=> Track download counts with non-namespaced dependency

package.json
I accidentally clobbered some changes from #449 by rebasing. This should be the correct dependency.
=> Include the correct dummy package

config.js, index.js, src/trace-writer.js, test/test-agent-metadata.js, test/test-trace-writer.js
This change adds a serviceContext field in the Trace Agent's configuration, in the same manner of the Debug Agent.
=> Add serviceContext option

.travis.yml, bin/run-test.sh, package.json, system-test/trace-express.js, test/test-agent-stopped.js, test/test-config-credentials.js, test/test-no-self-tracing.js, test/test-plugins-no-project-num.js, test/test-trace-uncaught-exception.js
Second attempt at #487, but travis on-merge tests should pass now.
=> Add a system-test

config.js
- This merely updates the comments in the configuration
comments with proper spelling.
Note: CLA signed.
=> Fix typos in configuration comments

system-test/trace-express.js
This way we can avoid globally setting GCLOUD_PROJECT and
GOOGLE_APPLICATION_CREDENTIALS in travis.yml. Having those env. vars.
set can cause the code to use different paths.
=> system-tests to use custom env. vars.

bin/run-test.sh
Following from #489, this PR also runs system-tests when testing locally.
=> also run system test locally

README.md
Added an example CLI for running under GKE.
=> docs: Elaboration on GKE Scopes + Syntax Highlighting

.gitignore, src/plugins/plugin-connect.js, src/plugins/plugin-express.js, src/plugins/plugin-hapi.js, src/plugins/plugin-koa.js, src/plugins/plugin-restify.js
Use apply rather than named parameters – we were missing the callback argument.
=> fix patching of res.end

src/trace-agent.js, src/trace-writer.js, test/plugins/common.js, test/plugins/test-trace-generic-pool.js, test/test-trace-writer.js
This change makes TraceWriter a singleton.
=> make TraceWriter a singleton

README.md
=> This module is now in beta

commitlint.config.js, package-lock.json, package.json
Use https://conventionalcommits.org/ with the [Angular style][].
Use `commitlint` to ensure that the commit messages follow the style
`husky` to ensure the lint is applied at git commit time.
To reedit the commit message after a lint failure, one can do something
like:
```
git commit --edit --file=.git/COMMIT_EDITMSG'
```
[Angular style]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
=> build: use conventional commit

src/trace-plugin-loader.js
=> Avoid throwing on malformed version in package json

test/plugins/common.js, test/test-cls-ah.js
=> test: restore Function#length property in wrapped mocha test functions when using continuation-local-storage with node 8

config.ts, index.ts, package.json, src/index.d.ts, src/span-data.ts, src/trace-api.ts, src/trace-plugin-loader.ts, src/trace-writer.ts, src/types.d.ts, test/override-gcp-metadata.ts, test/plugins/common.ts, test/test-agent-stopped.ts, test/test-config-max-label-size.ts, test/test-index.ts, test/test-span-data.ts, test/test-trace-api.ts, test/test-trace-writer.ts, test/test-unpatch.ts
I'd recommend looking at the commits separately.
=> refactor: ts conversion of config, trace-writer, span-data

config.ts
Various changes to in-code documentation to hopefully make things clearer. `ignoreUrls` is the important one.
Addresses #574
@GoogleCloudPlatform/node-team PTAL
=> docs: update config.ts

.travis.yml, package-lock.json, package.json, src/types.d.ts, test/override-gcp-metadata.ts
=> chore: upgrade gcp-metadata to 0.4

config.ts, package-lock.json, package.json, src/cls-ah.ts, src/plugin-types.ts, src/span-data.ts, src/trace-api.ts, src/trace-plugin-loader.ts, src/trace-span.ts, src/trace-writer.ts, src/trace.ts, src/tracing-policy.ts, src/util.ts
This is part of the work to enable greenkeeper... wanted to keep things separate as it appears that greenkeeper activation has distinct action items besides more style rules.
Reviewers: only the second commit (`refactor: manual changes to satisfy ts style guide`) has substantial manual changes.
=> style: upgrade to gts@0.5

src/cls-ah.ts
Fixes #600 for `async_hooks`-based context tracking.
Background -- got 7+ does gzip decompression by piping the `http.IncomingMessage` stream through an `unzip` transform, and then through a `stream.PassThrough` transform. To make the shape of the resulting `stream.PassThrough` stream look like `http.IncomingMessage`, it copies enumerable properties from the initial `http.IncomingMessage` stream to the new one. Listener functions like `on` are not enumerable, so they don't get copied to the `stream.PassThrough` (and they shouldn't be). [[source](https://github.com/sindresorhus/decompress-response/blob/master/index.js)]
Our way of patching event emitters causes functions like '`on`' to be enumerable, so the `stream.PassThrough` object has the wrong methods on it. This causes gzip …
=> fix: use shimmer to wrap event emitters in async_hooks-based cls

src/trace-api.ts
Tests to come in a follow-on.
Adresses: #603.
=> fix: avoid adding child spans to closed root

js-green-licenses.json, package-lock.json, package.json
The `log-driver` package must be whitelisted, which is a dep of
`@google-cloud/common`.
=> chore: license check in posttest

README.md, src/plugins/plugin-mongodb-core.ts, test/fixtures/plugin-fixtures.json, test/plugins/test-trace-mongodb.ts, test/plugins/test-trace-mongoose.ts
Fixes #758 
This PR is just a version bump for the supported `mongodb-core` version. I recommend `?w=1` (ignore whitespace) when looking at the diff view.
=> feat: support mongodb-core@3

package.json
See #779. Also, Mocha types are causing issues for the time being.
=> chore: fix a few package versions

package-lock.json, package.json
[Release Notes](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/releases/tag/untagged-3227bbd83264dfa08957)
=> chore: 2.11.0 release proposal

package.json
=> fix(package): update @google-cloud/common to version 0.20.3

package.json
[Release Notes](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/releases/edit/untagged-946abdc950e4dd2fb028)
=> chore: 3.0.0 release proposal

package-lock.json, package.json
[Release Notes](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/releases/tag/untagged-fc404273aaed780162a8)
=> chore: 3.1.0 release proposal

scripts/index.ts, test/plugins/test-trace-http2.ts
=> test: don't require long-door key to run system tests

package.json
~~[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-4840d641b9cf59bbf500)~~
[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/edit/untagged-d6583793a22b6288331e)
=> chore: 3.2.0 release proposal

src/trace-api.ts, test/test-trace-api.ts
=> fix: swap log levels for two log points

package.json
[Release Proposal](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-342b4348fe6bd3751429)
=> chore: 3.2.1 release proposal

package.json, src/trace-writer.ts
=> fix(deps): update dependency gcp-metadata to ^0.9.0

src/tracing-policy.ts, test/test-trace-policy.ts
=>  fix: allow sampling rate to be less than 1

.circleci/config.yml
cc/ @JustinBeckwith -- I did not think #901 should have landed without changes.
=> Revert "chore: update the CircleCI config"

package.json
~~[Release Proposal](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-04e7f3d89c544a2f494e)~~
[Release Proposal](https://github.com/googleapis/cloud-trace-nodejs/releases/edit/untagged-a608aa42c2de8d9e75cd)
=> chore: 3.3.0 release proposal

README.md
=> doc: fix samplingRate comment in README

package.json
[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-7c096458ccb06cfe01b1)
=> chore: 3.3.1 release proposal

samples/app.js
Fixes googleapis/google-cloud-node#2869 (it's a good idea to open an issue first for discussion)
Fixes https://github.com/googleapis/cloud-trace-nodejs
=> docs(samples): updated samples code to use async await

samples/app.js, samples/snippets.js
Update region tags to match our samples tracker.
=> Update region tags

src/plugins/plugin-express.ts, src/plugins/plugin-koa.ts
=> fix: #942 - use req.ip in express and koa plugin

README.md
In response to: https://stackoverflow.com/questions/52988854/google-cloud-trace-custom-trace-only-works-a-few-times
=> doc: clarify custom root spans

src/config.ts, src/span-data.ts, src/trace-writer.ts, test/plugins/common.ts, test/plugins/test-trace-http2.ts, test/test-span-data.ts, test/test-trace-uncaught-exception.ts, test/test-trace-writer.ts
=> feat: support child spans with tail latencies

README.md
added a note about using this in bundled code.
anything you think i should delete/reword would be welcome
=> docs: note on using trace in bundled server code

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/support_request.md, .github/PULL_REQUEST_TEMPLATE.md
These are used in all of our other nodejs repos :)
=> chore: add github issue templates

package.json
[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-d4e1a4e3951dbfd726fa)
=> chore: 4.0.1 release proposal

test/plugins/test-trace-http.ts
Strangely, in Kokoro CI, `http.get` doesn't emit an error when there is no target. This is true regardless of whether tracing is enabled, so this test just ensures that behavior is the same whether or not tracing is enabled, not whether that behavior is correct.
__Note__: Kokoro CI results can be ignored
=> test: don't timeout no-target http test if error not emitted

package.json, samples/package.json, samples/test/test.js
This PR adds a smoke test in the same way as in https://github.com/googleapis/cloud-debug-nodejs/pull/663.
__Note__: Kokoro CI results can be ignored
=> test: add smoke test for app sample

src/config.ts, src/index.ts, src/tracing.ts, test/test-modules-loaded-before-agent.ts
=> feat: add config.disableUntracedModulesWarn

package.json
[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-33467795aee74c9d4f91)
=> chore: 4.1.0 release proposal

test/test-trace-writer.ts
google-auth-library@5.1.1 made a private method name change which affects our tests, this updates our test to accomadate for this change.
=> test: accomodate private method name change

.gitignore, .readme-partials.yaml, .repo-metadata.json, README.md, samples/README.md, synth.metadata, synth.py
Fixes #523 
The docs failure requires this PR to land to pass 🤷‍♂
=> fix(docs): standardize README and add repo metadata

package.json, src/trace-writer.ts, test/test-trace-writer.ts
This should alleviate current test issues.
=> refactor: use teeny-request types

test/fixtures/plugin-fixtures.json, test/plugins/test-trace-mongoose.ts
=> test: temporarily pin mongoose@5.6

package.json
=> chore(deps): update dependency source-map-support to v0.5.16

package.json
[Release Notes](https://github.com/googleapis/cloud-trace-nodejs/releases/tag/untagged-83dc761e21d85b120bc6)
=> chore: 4.2.3 release proposal

src/plugins/plugin-pg.ts
=> fix: handle pg 7.16.0+ undefined Result#fields

.readme-partials.yaml, README.md, src/plugins/plugin-restify.ts, test/fixtures/plugin-fixtures.json, test/test-trace-web-frameworks.ts, test/web-frameworks/restify.ts
The author is having CLA issues in #1216, so I'm floating this for our next release.
=> feat: support restify 8

src/trace-api.ts, test/test-trace-api.ts
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #1265
=> feat: downgrade soft/hard span limit logs to warn level

test/test-span-data.ts
=> fix(tests): Hex value assertion was used on decimal string
